### PR TITLE
Initial addition of STM32 access via SPI

### PR DESCRIPTION
**Pull request by cafe-alpha**
Also features minimal changes here and there.
STM32 firmware is not ready yet. In advance, thank your for being patient until that time

### CODE REVIEW

**Comment by hitomi2500** [comment]
It's big. I may be wrong, but imho pull requests shouldn't be that big, it's hard to dissect them into actual changes. Nevertheless, i have some issues.

1) Is it keeping STM32 libraries really necessary? CMSIS and HAL alone takes 134 MB of space, and most of it is unused. That's what i'd call repo pollution. And we will miss every future update. There are 2 ways out that i see here : 
a) Include [ST's repo](https://github.com/STMicroelectronics/STM32CubeF4) as a submodule, that way we will receive any update immediately, and we don't have to track any change they made and keep the library in our files. There is a chance their update will broke something on our side, but we can always backtrack in time with GIT magic.
b) Add a project for some kind of auto-tool, that downloads, installs and updates the libraries automatically. The good choise is STM32CubeIDE.
Either is fine by me. Relying on CubeIDE might be not quite open, but it will suffice. What do you think?

2) I believe that keeping v12 in the same repo is fundamentally wrong. It's basically becomes the subfolder that contans the same files, but have no connection to the master code. Tracing changes becomes a horror. What should we do with v12 is find the point in the master branch that differs minimally with v12,  and add v12 as a new sub-branch from that point. This can be done after the merge, so i think we should remove v12 folder, merge the repos, and add the subbranch later. 

3) The more i think about it. the more i suspect that forking the repo was the wrong idea. I think we should both continue working in my (or yours, whichever makes more sense) repo together. Branching is more convenient for co-working, while forking is for creating spin-offs.

Since most things i propose require commiting to your repo before merging, i won't do anything until we decide how should we proceed.

**Comment by cafe-alpha** [comment]
I do agree that it's a bit huge for a single commit, sorry.

The interest of adding STM32 libraries is to provide all sources required to compile the project. Using latest libraries from official repo is good to get latest bugfixes and improvements, but may cause troubles in case of API changes or regression for a particular module on a particular device etc. But trimming the sources not used would had be a good idea because as you indicated, majority of STM32 library sources are not used.
However, I prefer solution a (to include ST's repo) because so far I was simply developing with a makefile and my favorite text editor, and am happy with this minimalistic development environment.

v1.2 sources and PCBs are completely things from the past. I only have a couple of these boards which are still waiting for appropriate firmware and eventually some debug but to be honest I prefer to spend my time on latest iteration than on them.
So it's OK to merge them "later", or simply completely forget about this folder.

I think too that we share enough development goals together to continue on the same repository. I would suggest to continue on your repository because this is where Wasca started, and also because tidying mine from unnecessary things would take more time than simply re-commiting latest project files.
... but please let me know the directions to do that. As you may have noticed, I'm not that familiar with git.

**Comment by hitomi2500** [comment]
Ok, before merging I will pull your fork, remove v12, detach STM32 libs (i will check that everything compiles with a submodule), and commit it to your repo. Then i will merge our repos together, and after that you can clone my repo instead or yours, and continue working there. 

If you have any pending commits /changes, please do them soon, or keep them as an offline patches, so that they could be applied to my repo later. And you should stop changing the code while i do the merge. So i will try to proceed as fast as possible.

**Comment by cafe-alpha** [comment]
The only change not committed yet is the data integrity check when loading boot ROM. And as I need to verify on latest hardware if that's required or not, let's start with current code base and eventually add this integrity check if it happens to be necessary.

In advance thank you for updating your repository with relevant source files. I sincerely hope a prosperous continuation of the development from there.

**Comment by hitomi2500** [comment]
Done. Please checkout hitomi2500/wasca, switch to the branch `v1_4_migration` and verify that everything is intact. When your git client asks you if submodules should be updated, answer positively. If it will not, and the  `mcu_firmware/STM32CubeF4` folder is empty,  run `git submodule update --init --recursive` command in the repository root. This command will fill the content of the folder with the latest ST repo content.

**Comment by cafe-alpha** [comment]
Local files from latest repository compile correctly. Thank you for the merge as well as the instructions to retrieve submodule source files !

**Pull request merged**
